name: ai-agent-streamlit-v2
services:
- name: web
  source_dir: /
  github:
    repo: mdinu-hash/db_agent_v1
    branch: main
    deploy_on_push: true
  run_command: streamlit run streamlit_demo_v2.py --server.port=8080 --server.address=0.0.0.0
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: LANGSMITH_API_KEY  
    scope: RUN_TIME
    type: SECRET
  - key: CONNECTION_STRING_DB
    scope: RUN_TIME
    type: SECRET
  - key: LANGSMITH_PROJECT
    scope: RUN_TIME
    value: "db_agent_v2"
  - key: LANGSMITH_TRACING
    scope: RUN_TIME  
    value: "true"
  - key: LANGSMITH_ENDPOINT
    scope: RUN_TIME
    value: "https://api.smith.langchain.com"