let
    // Reference your existing dim_employee table
    Source = DIM_EMPLOYEE,

    // Filter for current employees only
    FilterCurrent = Table.SelectRows(Source, each ([CURRENT_FLAG] = true)),

    // Function to recursively get all reporting paths below an employee
    GetAllPaths = (EmpKey as number, optional CurrentPath as list) =>
        let
            Path = if CurrentPath = null then {} else CurrentPath,

            // Get direct reports of current employee
            DirectReports = Table.SelectRows(FilterCurrent, each [SUPERVISOR_EMPLOYEE_KEY] = EmpKey),
            DirectReportKeys = DirectReports[EMPLOYEE_KEY],

            Result = if List.Count(DirectReportKeys) = 0 then
                // No reports - return the current path (or empty if at top)
                if List.Count(Path) = 0 then {} else {Path}
            else
                // Has reports - recursively get all paths through each report
                let
                    AllSubPaths = List.Transform(
                        DirectReportKeys,
                        each @GetAllPaths(_, Path & {_})
                    ),
                    FlattenedPaths = List.Combine(AllSubPaths)
                in
                    FlattenedPaths
        in
            Result,

    // Get all employees and their downward reporting paths
    AllEmployees = Table.AddColumn(FilterCurrent, "ReportingPaths", each GetAllPaths([EMPLOYEE_KEY])),

    // Expand so each path becomes its own row
    ExpandPaths = Table.AddColumn(AllEmployees, "PathExpanded", each
        if List.Count([ReportingPaths]) = 0 then {null} else [ReportingPaths]
    ),

    ExpandToRows = Table.ExpandListColumn(ExpandPaths, "PathExpanded"),

    // Add columns for each level in the hierarchy
    AddLevel1 = Table.AddColumn(ExpandToRows, "EMPLOYEE_FULL_NAME_LVL_1", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 1 then
            let
                EmpKey = [PathExpanded]{0},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel2 = Table.AddColumn(AddLevel1, "EMPLOYEE_FULL_NAME_LVL_2", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 2 then
            let
                EmpKey = [PathExpanded]{1},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel3 = Table.AddColumn(AddLevel2, "EMPLOYEE_FULL_NAME_LVL_3", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 3 then
            let
                EmpKey = [PathExpanded]{2},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel4 = Table.AddColumn(AddLevel3, "EMPLOYEE_FULL_NAME_LVL_4", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 4 then
            let
                EmpKey = [PathExpanded]{3},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel5 = Table.AddColumn(AddLevel4, "EMPLOYEE_FULL_NAME_LVL_5", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 5 then
            let
                EmpKey = [PathExpanded]{4},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel6 = Table.AddColumn(AddLevel5, "EMPLOYEE_FULL_NAME_LVL_6", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 6 then
            let
                EmpKey = [PathExpanded]{5},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel7 = Table.AddColumn(AddLevel6, "EMPLOYEE_FULL_NAME_LVL_7", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 7 then
            let
                EmpKey = [PathExpanded]{6},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel8 = Table.AddColumn(AddLevel7, "EMPLOYEE_FULL_NAME_LVL_8", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 8 then
            let
                EmpKey = [PathExpanded]{7},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel9 = Table.AddColumn(AddLevel8, "EMPLOYEE_FULL_NAME_LVL_9", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 9 then
            let
                EmpKey = [PathExpanded]{8},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel10 = Table.AddColumn(AddLevel9, "EMPLOYEE_FULL_NAME_LVL_10", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 10 then
            let
                EmpKey = [PathExpanded]{9},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    AddLevel11 = Table.AddColumn(AddLevel10, "EMPLOYEE_FULL_NAME_LVL_11", each
        if [PathExpanded] <> null and List.Count([PathExpanded]) >= 11 then
            let
                EmpKey = [PathExpanded]{10},
                EmpRow = try Table.SelectRows(FilterCurrent, (r) => r[EMPLOYEE_KEY] = EmpKey){0} otherwise null
            in
                if EmpRow <> null then EmpRow[EMPLOYEE_FULL_NAME] else null
        else null
    ),

    // Keep only needed columns
    SelectColumns = Table.SelectColumns(AddLevel11, {
        "EMPLOYEE_KEY",
        "EMPLOYEE_FULL_NAME_LVL_1",
        "EMPLOYEE_FULL_NAME_LVL_2",
        "EMPLOYEE_FULL_NAME_LVL_3",
        "EMPLOYEE_FULL_NAME_LVL_4",
        "EMPLOYEE_FULL_NAME_LVL_5",
        "EMPLOYEE_FULL_NAME_LVL_6",
        "EMPLOYEE_FULL_NAME_LVL_7",
        "EMPLOYEE_FULL_NAME_LVL_8",
        "EMPLOYEE_FULL_NAME_LVL_9",
        "EMPLOYEE_FULL_NAME_LVL_10",
        "EMPLOYEE_FULL_NAME_LVL_11"
    })
in
    SelectColumns
